---
version: '3.5'
services:

  connect:
    image: confluentinc/cp-enterprise-replicator:${TAG}
    command: "bash -c 'cp /usr/share/java/kafka-connect-replicator/replicator-rest-extension-*.jar /etc/kafka-connect/jars/; /etc/confluent/docker/run'"
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/java/
      CONNECT_REST_EXTENSION_CLASSES: io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension