---
version: '3.5'
services:

  haproxy:
    image: haproxy
    hostname: haproxy
    container_name: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ../../ccloud/replicator/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  connect:
    image: confluentinc/cp-enterprise-replicator:${TAG}
    volumes:
      - ../../ccloud/replicator/kafka-schema-registry-client-5.4.1-cp1.jar:/usr/share/java/kafka-connect-replicator/kafka-schema-registry-client-5.4.1.jar
      - ../../ccloud/replicator/kafka-schema-registry-5.4.1-cp1.jar:/usr/share/java/kafka-connect-replicator/kafka-schema-registry-5.4.1.jar
      - ../../ccloud/replicator/kafka-schema-registry-client-5.4.1-cp1.jar:/usr/share/java/schema-registry/kafka-schema-registry-client-5.4.1.jar
      - ../../ccloud/replicator/kafka-schema-registry-5.4.1-cp1.jar:/usr/share/java/schema-registry/kafka-schema-registry-5.4.1.jar
    command: "bash -c 'cp /usr/share/java/kafka-connect-replicator/replicator-rest-extension-*.jar /etc/kafka-connect/jars/; /etc/confluent/docker/run'"
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/java/
      CONNECT_REST_EXTENSION_CLASSES: io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension